---
title: "Data_Replication"
author: "Dom-Romanello"
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(
    fig.path = "img/"
)
```

Figure A1

```{r}

A1 = ggplot() + 
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Max66), color = "blue", shape = 18) +
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Max82A), color = "orange", shape = 18) +
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Max82B), color = "gray", shape = 18) + 
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Max87), color = "yellow", shape = 18) + 
  xlab('Renmark Temperature (C)') +
  ylab('Recorded Ambient Temperature (C)') + 
  expand_limits(x=c(15:45)) +
  expand_limits(y=c(15:45)) 


print(A1)

PearMax66 <- cor.test(Temp$Max_Renmark, Temp$Max66, method = "pearson", conf.level = 0.95)
PearMax82A <- cor.test(Temp$Max_Renmark, Temp$Max82A, method = "pearson", conf.level = 0.95)
PearMax82B <- cor.test(Temp$Max_Renmark, Temp$Max82B, method = "pearson", conf.level = 0.95)
PearMax87 <- cor.test(Temp$Max_Renmark, Temp$Max87, method = "pearson", conf.level = 0.95)





```

Figure A2

```{r}

A2 = ggplot() + 
  geom_point(data = Temp, aes(x = Temp$MinR, y = Temp$M66), group = 1, color = "blue", shape = 18) +
  geom_point(data = Temp, aes(x = Temp$MinR, y = Temp$M82A), group = 1, color = "orange", shape = 18) +
  geom_point(data = Temp, aes(x = Temp$MinR, y = Temp$M82B), group = 1, color = "gray", shape = 18) + 
  geom_point(data = Temp, aes(x = Temp$MinR, y = Temp$M87), group = 1, color = "yellow", shape = 18) + 
  xlab('Renmark Temperature (C)') +
  ylab('Recorded Ambient Temperature (C)') + 
  expand_limits(x=c(0:20)) +
  expand_limits(y=c(0:20))

print(A2)

cor.test(Temp$MinR, Temp$M66, method = "pearson", conf.level = 0.95)
cor.test(Temp$MinR, Temp$M82A, method = "pearson", conf.level = 0.95)
cor.test(Temp$MinR, Temp$M82B, method = "pearson", conf.level = 0.95)
cor.test(Temp$MinR, Temp$M87, method = "pearson", conf.level = 0.95)


```

Figure 3: Average buffering provided by tree hollows at different depths during night (positive values above the x-axis) and day (negative values below the x-axis) for 28 days (3–31 October 2013).

```{r}

DF <- data.frame(Depth=rep(c("0","10", "20","30","40")),
           Day66=c(0,-1.7,-1.4,-2.9,-3), 
            Night66=c(0,0.8,0.4,1.4,2), 
              Day82A=c(0,-3.7,-3.9,-4.1,-4.4),
                Night82A=c(0,3.3,2.9,3.1,3.1),
                  Day82B=c(0,-3.4,-3.7,-4,-4.3), 
                    Night82B=c(0,3,2.9,2.9,2.8), 
                      Day87=c(0,-2.4,-2.7,-3.3,-3.1),
                        Night87=c(0,1,2,1.9,1.9))
head(DF)



A = ggplot() + 
  geom_point(data = DF, aes(x = Depth, y = Day66), color = "dark gray", shape = 18) +
  geom_point(data = DF, aes(x = Depth, y = Night66), color = "dark gray", shape = 18) +
  geom_point(data = DF, aes(x = Depth, y = Day82A), color = "black", shape = 15) +
  geom_point(data = DF, aes(x = Depth, y = Night82A), color = "black", shape = 15) +
  geom_point(data = DF, aes(x = Depth, y = Day82B), color = "black", shape = 17) +
  geom_point(data = DF, aes(x = Depth, y = Night82B), color = "black", shape = 17) +
  geom_point(data = DF, aes(x = Depth, y = Day87), color = "black") +
  geom_point(data = DF, aes(x = Depth, y = Night87), color = "black") +
  geom_line(data = DF, aes(x = Depth, y = Day66), group=1, color = "dark gray") +
  geom_line(data = DF, aes(x = Depth, y = Night66), group=1, color = "dark gray") +
  geom_line(data = DF, aes(x = Depth, y = Day82A), group=1, color = "black") +
  geom_line(data = DF, aes(x = Depth, y = Night82A), group=1, color = "black") +
  geom_line(data = DF, aes(x = Depth, y = Day82B), group=1, color = "black", linetype = "dotted") +
  geom_line(data = DF, aes(x = Depth, y = Night82B), group=1, color = "black", linetype = "dotted") +
  geom_line(data = DF, aes(x = Depth, y = Day87), group=1, color = "black", linetype = "dashed") +
  geom_line(data = DF, aes(x = Depth, y = Night87), group=1, color = "black", linetype = "dashed") +
  xlab('Hollow Depth (cm)') +
  ylab('Average Buffering (C)') 

print(A)


```

Figure 4

```{r}

Temp <- read.csv("~/Desktop/R-Data-Analysis/Data_Replication.csv")

head(Temp)


B = ggplot() + 
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Buff66), color = "dark gray", shape =    18) +
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Buff82A), color = "dark gray", shape =    18) +
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Buff82B), color = "dark gray", shape =    18) + 
  geom_point(data = Temp, aes(x = Temp$Max_Renmark, y = Temp$Buff87), color = "dark gray", shape =    18) + 
  xlab('Maximum Daytime Temperature (C)') +
  ylab('Maximum Buffering (C)') + 
  expand_limits(x=c(15:40)) +
  expand_limits(y=c(-18:2))

print(B)


```

Figure 4: Another attempt. 

```{r}
df <- data.frame(MaxAmbient=c(32.4,25,24.8,26.9,36.2,22.9,23.6,30.6,20.7,20,25.9,32.7,21,27.3,32.6,39.7,31.5,26.5,21.8,20.3,22.3,24.5,25.8,25.3,23.6,24.7,26.1)) MaxDayBuff66=c(31.1,25.1,25.6,30.6,35.6,21.6,25.6,30.6,20.6,21.1,28.1,31.1,22.6,30.6,33.6,39.1,28.6,23.6,21.6,24.6,27.6,29.1,23.1,23.6,25.6,296, 31.1)
            
head(df)

B = ggplot() + 
  geom_point(data = DF, aes(x = MaxAmbient, y = MaxDayBuff66), color = "dark gray", shape = 18) 

print(B)

```

ANOVA

```{r}

Temp <- read.csv("~/Desktop/R-Data-Analysis/Data_Replication.csv")

head(Temp)

summary(Temp)

aov <- aov(data = Temp, Max66 ~ Max82A)
summary(aov)

aov <- aov(data = Temp, Max82A ~ Min82A)
summary(aov)

aov <- aov(data = Temp, Max82B ~ Min82B)
summary(aov)

aov <- aov(data = Temp, Max87 ~ Min87)
summary(aov)

```
