---
title: "Module-15"
author: "Dom-Romanello"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(readr)
library(ggplot2)
library(gridExtra)
library(manipulate)
library(lmodel2)


f <- "https://raw.githubusercontent.com/difiore/ADA-2019/master/zombies.csv"
d <- read_csv(f, col_names = TRUE)

head(d)

plot(data = d, height ~ weight)

w <- d$weight
h <- d$height
n <- length(w)  # or length(h)
cov_wh <- sum((w - mean(w)) * (h - mean(h)))/(n - 1)
cov_wh

corwh <- cov(w,h)

corwh/(sd(w)*sd(h))

cor(w, h, method = "kendall")

cor(w, h, method = "spearman")

y <- h - mean(h)
x <- w - mean(w)
z <- data.frame(cbind(x, y))
g <- ggplot(data = z, aes(x = x, y = y)) + geom_point()
g

slope.test <- function(beta1) {
    g <- ggplot(data = z, aes(x = x, y = y))
    g <- g + geom_point()
    g <- g + geom_abline(intercept = 0, slope = beta1, size = 1, colour = "blue", 
        alpha = 1/2)
    ols <- sum((y - beta1 * x)^2)
    g <- g + ggtitle(paste("Slope = ", beta1, "\nSum of Squared Deviations = ", 
        round(ols, 3)))
    g
}

manipulate(slope.test(beta1), beta1 = slider(-1, 1, initial = 0, step = 0.005))

b1 <- cov(x,y)/var(x)

b1

b0<- (y-b1*x)

y1 <- b1*x

m <- lm(height ~ weight, data = d)
m

names(m)

m$coefficients

head(m$model)

g <- ggplot(data = d, aes(x = weight, y = height))
g <- g + geom_point()
g <- g + geom_smooth(method = "lm", formula = y ~ x)
g

library(lmodel2)  # load the lmodel2 package
# Run the regression
mII <- lmodel2(height ~ weight, data = d, range.y = "relative", range.x = "relative", 
    nperm = 1000)
mII

par(mfrow = c(2, 2))
plot(mII, "OLS")
plot(mII, "RMA")
plot(mII, "SMA")
plot(mII, "MA")

```


```{r}

h <- d$height
a <- d$age

beta1 <- cor(a,h) * (sd(h)/sd(a))
beta1

beta1 <- cor(d$height, d$age) * sd(d$height)/sd(d$age)
beta1

beta0 <- mean(h) - beta1 * mean(a)
beta0

n <- lm(height ~ age, data = d)
n

cor(w,a, method="pearson")

names(n)

n$coefficients

head(n$model)

males <- filter(d, gender == "Male")
m <- lm(h ~ a, data = males)
m

females <- filter(d, gender == "Female")
m <- lm(h ~ a, data = females)
m

```

```{r}

m <- lm(data = d, height ~ weight)
summary(m)

t <- coef(summary(m))
t <- data.frame(unlist(t))
colnames(t) <- c("Est", "SE", "t", "p")
t 

t$calct <- (t$Est - 0)/t$SE  # calculate t on our own and add to the dataframe
t$calcp <- 2 * pt(t$calct, df = 998, lower.tail = FALSE)
t

alpha <- 0.05
# extract CI from summary()
t$lmCI <- confint(m, level = 1 - alpha)  # using the results of lm()
# calc CI by hand
attributes(t$lmCI)

lowerCI <- t$Est - qt(1 - alpha/2, df = 998) * t$SE
upperCI <- t$Est + qt(1 - alpha/2, df = 998) * t$SE
t$calcCI <- cbind(lowerCI, upperCI)
dimnames(t$calcCI)[[1]] <- c("(Intercept)", "weight")
dimnames(t$calcCI)[[2]] <- c("2.5 %", "97.5 %")
t[, 7:8]

```


```{r}

beta0 <- t$Est[1]
beta1 <- t$Est[2]
h_hat <- beta1 * 150 + beta0
h_hat

h_hat_diff <- (beta1 * 220 + beta0) - (beta1 * 180 + beta0)

h_hat_diff

m <- lm(data = d, height ~ weight)
h_hat <- predict(m, newdata = data.frame(weight = d$weight))
df <- data.frame(cbind(d$weight, d$height, h_hat))
names(df) <- c("x", "y", "yhat")
head(df)

g <- ggplot(data = df, aes(x = x, y = yhat))
g <- g + geom_point()
g <- g + geom_point(aes(x = x, y = y), colour = "red")
g <- g + geom_segment(aes(x = x, y = yhat, xend = x, yend = y))
g

ci <- predict(m, newdata = data.frame(weight = 150), interval = "confidence", 
    level = 0.95)  # for a single value
ci

ci <- predict(m, newdata = data.frame(weight = d$weight), interval = "confidence", 
    level = 0.95)  # for a vector of values
head(ci)

df <- cbind(df, ci)
names(df) <- c("x", "y", "yhat", "CIfit", "CIlwr", "CIupr")
head(df)

g <- ggplot(data = df, aes(x = x, y = y))
g <- g + geom_point(alpha = 0.5)
g <- g + geom_line(aes(x = x, y = CIfit), colour = "black")
g <- g + geom_line(aes(x = x, y = CIlwr), colour = "blue")
g <- g + geom_line(aes(x = x, y = CIupr), colour = "blue")
g

pi <- predict(m, newdata = data.frame(weight = 150), interval = "prediction", 
    level = 0.95)  # for a single value
pi

pi <- predict(m, newdata = data.frame(weight = d$weight), interval = "prediction", 
    level = 0.95)  # for a vector of values
head(pi)

df <- cbind(df, pi)
names(df) <- c("x", "y", "yhat", "CIfit", "CIlwr", "CIupr", "PIfit", "PIlwr", 
    "PIupr")
head(df)

g <- g + geom_line(data = df, aes(x = x, y = PIlwr), colour = "red")
g <- g + geom_line(data = df, aes(x = x, y = PIupr), colour = "red")
g

```

```{r}

m <- lm(data = d, h ~ a)
summary(m)



pi <- predict(m, newdata = data.frame(weight = d$m), interval = "prediction", 
    level = 0.95)  # for a vector of values
head(pi)




v <- seq(from = 10, to = 30, by = 1)
m <- lm(data = d, height ~ age)
ci <- predict(m, newdata = data.frame(age = v), interval = "confidence", level = 0.95)
pi <- predict(m, newdata = data.frame(age = v), interval = "prediction", level = 0.95)
plot(data = d, height ~ age)
lines(x = v, y = ci[, 1], col = "black")
lines(x = v, y = ci[, 2], col = "blue")
lines(x = v, y = ci[, 3], col = "blue")
lines(x = v, y = pi[, 2], col = "red")
lines(x = v, y = pi[, 3], col = "red")


```


