---
title: "Module 12"
author: "Dom-Romanello"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(curl)
library(dplyr)


n <- 1000
mu <- 3.5
sigma <- 4
v <- rnorm(n, mu, sigma)
s <- sample(v, size = 30, replace = FALSE)

v

m <- mean(s)
m

sd<- sd(s)
sd

sem <- sd(s)/sqrt(length(s))
sem

lower <- m - qnorm(1 - 0.05/2) * sem  # (1-alpha)/2 each in the upper and lower tails of the distribution
upper <- m + qnorm(1 - 0.05/2) * sem  # (1-alpha)/2 each in the upper and lower tails of the distribution
ci <- c(lower, upper)
ci

lambda <- 14
n <- 10
pop_se <- sqrt(lambda/n)  # the estimated SE
pop_se

x <- NULL
for (i in 1:1000) {
    x[i] <- mean(rpois(n = n, lambda = lambda))
}
hist(x, breaks = seq(from = lambda - 4 * sqrt(lambda)/sqrt(n), to = lambda + 
    4 * sqrt(lambda)/sqrt(n), length.out = 20), probability = TRUE)

sd <- sd(x)

qqnorm(x)

n <- 100
pop_se <- sqrt(lambda/n)  # the estimated SE
pop_se

x <- NULL
for (i in 1:1000) {
    x[i] <- mean(rpois(n = n, lambda = lambda))
}
hist(x, breaks = seq(from = lambda - 4 * sqrt(lambda)/sqrt(n), to = lambda + 
    4 * sqrt(lambda)/sqrt(n), length.out = 20), probability = TRUE)

curve(dnorm(x, 0, 1), -4, 4, ylim = c(0, 0.8))
z <- (x - lambda)/pop_se
hist(z, breaks = seq(from = -4, to = 4, length.out = 20), probability = TRUE, 
    add = TRUE)

n <- 100
x <- NULL
for (i in 1:1000) {
    x[i] <- sum(rpois(n = n, lambda = lambda))
}
hist(x, breaks = seq(min(x), max(x), length.out = 20), probability = TRUE)

n <- 1000
x <- 856
phat <- x/n  # our estimate of pi
phat

est_pop_se <- sqrt((phat) * (1 - phat)/n)

curve(dnorm(x, mean = phat, sd = est_pop_se), phat - 4 * est_pop_se, phat + 
    4 * est_pop_se)
upper <- phat + qnorm(0.975) * est_pop_se
lower <- phat - qnorm(0.975) * est_pop_se
ci <- c(lower, upper)
polygon(cbind(c(ci[1], seq(from = ci[1], to = ci[2], length.out = 1000), ci[2]), 
    c(0, dnorm(seq(from = ci[1], to = ci[2], length.out = 1000), mean = phat, 
        sd = est_pop_se), 0)), border = "black", col = "gray")
ci



```

Use t distribution, family of curves like normal curves but sample size is low. 

```{r}

mu <- 0
sigma <- 1
curve(dnorm(x, mu, 1), mu - 4 * sigma, mu + 4 * sigma, main = "Normal Curve=red\nStudent's t=blue", 
    xlab = "x", ylab = "f(x)", col = "red", lwd = 3)
for (i in c(1, 2, 3, 4, 5, 10, 20, 100)) {
    curve(dt(x, df = i), mu - 4 * sigma, mu + 4 * sigma, main = "T Curve", xlab = "x", 
        ylab = "f(x)", add = TRUE, col = "blue", lty = 5)
}

n <- 1e+05
mu <- 3.5
sigma <- 4
x <- rnorm(n, mu, sigma)
sample_size <- 30
s <- sample(x, size = sample_size, replace = FALSE)
m <- mean(s)
m

lower <- m - qnorm(1 - 0.05/2) * sem  
upper <- m + qnorm(1 - 0.05/2) * sem  
ci_norm <- c(lower, upper)
ci_norm

lower <- m - qt(1 - 0.05/2, df = sample_size - 1 ) * sem
upper <- m + qt(1 - 0.05/2, df = sample_size - 1) * sem
ci_t <- c(lower, upper)
ci_t

library(curl)
f <- curl("https://raw.githubusercontent.com/difiore/ADA-2019/master/vervet-weights.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)

mean(d$weight)

mu <- 4.9
x <- d$weight
x
m <- mean(x)
m
s <- sd(x)
n <- length(x)
sem <- s/sqrt(n)
sem
z <- (m - mu)/sem
z

p <- 1 - pnorm(z)
p

p <- pnorm(z, lower.tail = FALSE)
p

p <- 1 - pt(z, df = n - 1)
p

p <- pt(z, df = n - 1, lower.tail = FALSE)
p

t <- t.test(x = x, mu = mu, alternative = "greater")
t


lower <- m - qt(1 - 0.05/2, df = n - 1) * sem
upper <- m + qt(1 - 0.05/2, df = n - 1) * sem
ci <- c(lower, upper)
ci

t <- t.test(x = x, mu = mu, alternative = "two.sided")
ci <- t$conf.int
ci

```

don't worry r has single built in function for t tests so you don't have to code all this